// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wafi_Solution_Project.Data;

#nullable disable

namespace Wafi_Solution_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Wafi_Solution_Project.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HolidayModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HolidayModelId");

                    b.ToTable("countriesD");
                });

            modelBuilder.Entity("Wafi_Solution_Project.Models.HolidayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("holidayD");
                });

            modelBuilder.Entity("Wafi_Solution_Project.Models.Countries", b =>
                {
                    b.HasOne("Wafi_Solution_Project.Models.HolidayModel", null)
                        .WithMany("Countrys")
                        .HasForeignKey("HolidayModelId");
                });

            modelBuilder.Entity("Wafi_Solution_Project.Models.HolidayModel", b =>
                {
                    b.Navigation("Countrys");
                });
#pragma warning restore 612, 618
        }
    }
}
